TICKERS = ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META"]
BENCHMARK = "SPY"

START_DATE = "2024-01-01"
END_DATE = "2026-01-01"
LOOKBACK_MOM = 252
SKIP_RECENT = 21
LOOKBACK_VOL = 60
FACTOR_NAMES = ['Size', 'Value', 'Momentum', 'Volatility']

