TICKERS = ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN", "META"]
BENCHMARK = "SPY"

START_DATE = "2020-01-01"
END_DATE = "2026-01-01"
LOOKBACK_MOM = 63
SKIP_RECENT = 5
LOOKBACK_VOL = 20
FACTOR_NAMES = ['Size', 'Value', 'Momentum', 'Volatility']

